// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 5a4729bb7867878ea92e49dd8dc66f388fe8fd255ab32292283ca573d17153d9

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func Dashboard(view DashboardView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/dashboard.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<!doctype html>\n<html lang=\"en\">\n<head>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:9:11
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (Head(view.Head))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:9:29
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</head>\n<body>\n  <a class=\"skip-link\" href=\"#main\">Skip to content</a>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:12:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteHeader(true, "dashboards", view.Organization.ID))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:12:62
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n  <main id=\"main\">\n    <nav class=\"breadcrumbs\" aria-label=\"Breadcrumb\"><a href=\"/app/?organization="); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:14:86
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:14:109
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Overview</a> <span aria-hidden=\"true\">/</span> <span aria-current=\"page\">"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:14:188
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Name)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:14:200
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</span></nav>\n    <header class=\"app-intro\"><div><p class=\"eyebrow\">"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:15:59
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Organization.Name)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:15:84
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, " · dashboard</p><h1>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:15:109
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Name)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:15:121
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</h1><p>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:15:133
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Description)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:15:152
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p></div><p><a class=\"button secondary\" href=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:15:203
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.ExportURL)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:15:220
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Export JSON</a></p></header>\n    <section class=\"dashboard-panels\" aria-label=\"Dashboard panels\">\n    "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:17:8
		if len(view.Panels) == 0 {
//line internal/site/dashboard.sando:17:37
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p>This dashboard has no panels yet.</p>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:17:80
		}
//line internal/site/dashboard.sando:17:84
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:18:8
		for _, panel := range view.Panels {
//line internal/site/dashboard.sando:18:46
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      <article class=\"signal-card\">\n        <p class=\"eyebrow\">"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:20:32
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (panel.Visualization)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:20:54
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p><h2>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:20:66
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (panel.Title)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:20:80
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</h2>\n        "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:21:12
			if panel.Stat != "" {
//line internal/site/dashboard.sando:21:36
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p class=\"stat\" aria-label=\"Current statistic\">"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:21:87
				if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (panel.Stat)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:21:100
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:21:107
			}
//line internal/site/dashboard.sando:21:111
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:22:12
			if len(panel.Chart.Points) > 0 {
//line internal/site/dashboard.sando:22:47
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        <figure class=\"meter-figure\">\n          <figcaption>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:24:27
				if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (panel.Chart.Label)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:24:47
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</figcaption>\n          <ol class=\"meter-chart\">\n          "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:26:14
				for _, point := range panel.Chart.Points {
//line internal/site/dashboard.sando:26:59
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n            <li><span class=\"meter-label\">"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:47
					if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (point.Label)); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:61
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</span><meter min=\"0\" max=\""); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:92
					if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (point.Maximum)); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:108
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" value=\""); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:121
					if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (point.Value)); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:135
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:141
					if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (point.Display)); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:157
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</meter><span class=\"meter-value\">"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:195
					if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (point.Display)); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:27:211
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</span></li>\n          "); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:28:14
				}
//line internal/site/dashboard.sando:28:18
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n          </ol>\n        </figure>\n        "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:31:12
			}
//line internal/site/dashboard.sando:31:16
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        <details><summary>Query</summary><pre><code>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:32:57
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (panel.Query)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:32:71
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</code></pre></details>\n        "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:33:13
			if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (ResultTable(panel.Table))); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:33:40
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      </article>\n    "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:35:8
		}
//line internal/site/dashboard.sando:35:12
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    </section>\n    "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:37:8
		if view.CanManage {
//line internal/site/dashboard.sando:37:30
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    <section class=\"section-grid\" aria-labelledby=\"edit-dashboard\">\n      <div><p class=\"eyebrow\">Dashboard workshop</p><h2 id=\"edit-dashboard\">Revise this view</h2><p>Every change includes revision "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:39:136
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Revision)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:39:152
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, ". If someone else saves first, Observatory asks you to reload instead of overwriting their work.</p></div>\n      <div class=\"editor-grid\">\n        <form class=\"editor-card\" method=\"post\" action=\"/app/dashboards/"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:41:77
			if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Slug)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:41:89
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "/\">\n          <h3>Dashboard details</h3>\n          <input type=\"hidden\" name=\"organization_id\" value=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:43:66
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:43:89
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:44:61
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ManageCSRF)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:44:79
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <input type=\"hidden\" name=\"dashboard_id\" value=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:45:63
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ID)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:45:73
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <input type=\"hidden\" name=\"expected_revision\" value=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:46:68
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Revision)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:46:84
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <label for=\"dashboard-edit-slug\">URL slug</label><input id=\"dashboard-edit-slug\" name=\"slug\" value=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:47:115
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Slug)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:47:127
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" required maxlength=\"63\" pattern=\"[a-z][a-z0-9-]+\">\n          <label for=\"dashboard-edit-name\">Name</label><input id=\"dashboard-edit-name\" name=\"name\" value=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:48:111
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Name)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:48:123
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" required maxlength=\"128\">\n          <label for=\"dashboard-edit-description\">Description</label><textarea id=\"dashboard-edit-description\" name=\"description\" required maxlength=\"1024\">"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:49:161
			if __himesan_error := __himesan_sando.WriteRCDATA(__himesan_writer, (view.Description)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:49:180
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</textarea>\n          <button type=\"submit\">Update dashboard details</button>\n        </form>\n        "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:52:12
			for index, panel := range view.Panels {
//line internal/site/dashboard.sando:52:54
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        <section class=\"editor-card\" aria-labelledby=\"panel-editor-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:53:72
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (index)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:53:80
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <h3 id=\"panel-editor-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:54:36
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (index)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:54:44
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Panel "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:54:56
				if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (index + 1)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:54:68
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</h3>\n          <form method=\"post\" action=\"/app/dashboards/"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:55:59
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Slug)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:55:71
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "/panels/"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:55:83
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (panel.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:55:94
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "/\">\n            <input type=\"hidden\" name=\"organization_id\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:56:68
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:56:91
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n            <input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:57:63
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ManageCSRF)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:57:81
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n            <input type=\"hidden\" name=\"dashboard_id\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:58:65
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:58:75
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n            <input type=\"hidden\" name=\"expected_revision\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:59:70
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Revision)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:59:86
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n            <label for=\"panel-title-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:60:41
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (index)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:60:49
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Title</label><input id=\"panel-title-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:60:91
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (index)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:60:99
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" name=\"panel_title\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:60:131
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (panel.Title)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:60:145
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" required maxlength=\"128\">\n            <label for=\"panel-query-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:61:41
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (index)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:61:49
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Saved query</label>\n            <select id=\"panel-query-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:62:41
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (index)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:62:49
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" name=\"saved_query_id\" required>\n            "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:63:16
				for _, item := range view.SavedQueries {
//line internal/site/dashboard.sando:63:59
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n              "); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:64:18
					if item.ID == panel.SavedQueryID {
//line internal/site/dashboard.sando:64:55
						if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\""); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:74
						if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (item.ID)); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:84
						if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" selected>"); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:99
						if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (item.Name)); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:111
						if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</option>"); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:123
					} else {
//line internal/site/dashboard.sando:64:134
						if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\""); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:153
						if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (item.ID)); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:163
						if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">"); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:169
						if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (item.Name)); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:181
						if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</option>"); __himesan_error != nil {
							return __himesan_error
						}
//line internal/site/dashboard.sando:64:193
					}
//line internal/site/dashboard.sando:64:197
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n            "); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:65:16
				}
//line internal/site/dashboard.sando:65:20
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n            </select>\n            <label for=\"panel-visualization-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:67:49
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (index)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:67:57
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Presentation</label>\n            <select id=\"panel-visualization-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:68:49
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (index)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:68:57
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" name=\"visualization\" required>\n              "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:69:18
				if panel.Visualization == "table" {
//line internal/site/dashboard.sando:69:56
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\"table\" selected>Table</option>"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:69:104
				} else {
//line internal/site/dashboard.sando:69:115
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\"table\">Table</option>"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:69:154
				}
//line internal/site/dashboard.sando:69:158
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n              "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:70:18
				if panel.Visualization == "stat" {
//line internal/site/dashboard.sando:70:55
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\"stat\" selected>Single statistic with table</option>"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:70:124
				} else {
//line internal/site/dashboard.sando:70:135
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\"stat\">Single statistic with table</option>"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:70:195
				}
//line internal/site/dashboard.sando:70:199
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n              "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:71:18
				if panel.Visualization == "timeseries" {
//line internal/site/dashboard.sando:71:61
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\"timeseries\" selected>Time series with table</option>"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:71:131
				} else {
//line internal/site/dashboard.sando:71:142
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\"timeseries\">Time series with table</option>"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:71:203
				}
//line internal/site/dashboard.sando:71:207
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n            </select>\n            <button type=\"submit\">Update panel</button>\n          </form>\n          <details>\n            <summary>Remove this panel</summary>\n            <p>This removes the panel from the dashboard definition. The saved query remains available.</p>\n            <form method=\"post\" action=\"/app/dashboards/"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:78:61
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Slug)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:78:73
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "/panels/"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:78:85
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (panel.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:78:96
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "/remove/\">\n              <input type=\"hidden\" name=\"organization_id\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:79:70
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:79:93
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n              <input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:80:65
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ManageCSRF)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:80:83
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n              <input type=\"hidden\" name=\"dashboard_id\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:81:67
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:81:77
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n              <input type=\"hidden\" name=\"expected_revision\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:82:72
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Revision)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:82:88
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n              <button class=\"secondary\" type=\"submit\">Confirm panel removal</button>\n            </form>\n          </details>\n        </section>\n        "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:87:12
			}
//line internal/site/dashboard.sando:87:16
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:88:12
			if len(view.Panels) < 16 {
//line internal/site/dashboard.sando:88:41
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        <form class=\"editor-card\" method=\"post\" action=\"/app/dashboards/"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:89:77
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Slug)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:89:89
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "/panels/\">\n          <h3>Add a panel</h3>\n          <input type=\"hidden\" name=\"organization_id\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:91:66
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:91:89
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:92:61
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ManageCSRF)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:92:79
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <input type=\"hidden\" name=\"dashboard_id\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:93:63
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:93:73
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <input type=\"hidden\" name=\"expected_revision\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:94:68
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Revision)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:94:84
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <label for=\"panel-add-title\">Title</label><input id=\"panel-add-title\" name=\"panel_title\" required maxlength=\"128\">\n          <label for=\"panel-add-query\">Saved query</label>\n          <select id=\"panel-add-query\" name=\"saved_query_id\" required><option value=\"\">Choose a saved query</option>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:97:120
				for _, item := range view.SavedQueries {
//line internal/site/dashboard.sando:97:163
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\""); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:97:182
					if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (item.ID)); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:97:192
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:97:198
					if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (item.Name)); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:97:210
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</option>"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:97:222
				}
//line internal/site/dashboard.sando:97:226
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</select>\n          <label for=\"panel-add-visualization\">Presentation</label>\n          <select id=\"panel-add-visualization\" name=\"visualization\" required><option value=\"table\">Table</option><option value=\"stat\">Single statistic with table</option><option value=\"timeseries\">Time series with table</option></select>\n          "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:100:14
				if len(view.SavedQueries) == 0 {
//line internal/site/dashboard.sando:100:49
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<button type=\"submit\" disabled>Add panel</button>"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:100:101
				} else {
//line internal/site/dashboard.sando:100:112
					if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<button type=\"submit\">Add panel</button>"); __himesan_error != nil {
						return __himesan_error
					}
//line internal/site/dashboard.sando:100:155
				}
//line internal/site/dashboard.sando:100:159
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        </form>\n        "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/dashboard.sando:102:12
			}
//line internal/site/dashboard.sando:102:16
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      </div>\n    </section>\n    "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/dashboard.sando:105:8
		}
//line internal/site/dashboard.sando:105:12
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n  </main>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:107:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteFooter())); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/dashboard.sando:107:22
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n</body>\n</html>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
