// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 970611f5a27597a2257f7ce7f38bc1184b99fa0801b9b0e3d09ea8bd53986827

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func Explore(view ExploreView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/explore.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<!doctype html>\n<html lang=\"en\">\n<head>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:9:11
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (Head(view.Head))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:9:29
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</head>\n<body>\n  <a class=\"skip-link\" href=\"#main\">Skip to content</a>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:12:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteHeader(true, "explore", view.Organization.ID))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:12:59
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n  <main id=\"main\">\n    <nav class=\"breadcrumbs\" aria-label=\"Breadcrumb\"><a href=\"/app/?organization="); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:14:86
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:14:109
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Overview</a><span aria-hidden=\"true\">/</span><span aria-current=\"page\">Explore</span></nav>\n    <section class=\"app-intro\" aria-labelledby=\"explore-title\">\n      <div><p class=\"eyebrow\">Query workshop · "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:16:53
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Organization.Name)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:16:78
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p><h1 id=\"explore-title\">Follow the evidence.</h1><p>Welcome, "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:16:146
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.DisplayName)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:16:165
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, ". Write one bounded query, run it on the server, and inspect both the result and its cost.</p></div>\n    </section>\n    <aside class=\"live-status\" data-events-url=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:18:53
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.EventsURL)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:18:70
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" hidden>\n      <p><strong>New observations are available.</strong> Run the query again when you are ready; Observatory will not replace the result beneath you.</p>\n    </aside>\n    <section class=\"explore-layout\" aria-labelledby=\"query-title\">\n      <div>\n        <p class=\"eyebrow\">Typed query</p>\n        <h2 id=\"query-title\">Ask a bounded question</h2>\n        <p>Queries stay out of the URL and access log. The same parser, authorization scope, sensitivity rules, and execution limits used by the API are applied here.</p>\n        <div class=\"quick-queries\" aria-label=\"Example queries\">\n          <form method=\"post\" action=\"/app/explore/?organization="); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:27:70
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:27:93
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:27:145
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.CSRFToken)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:27:162
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"query\" value=\"logs | window 1h | limit 50\"><button class=\"secondary\" type=\"submit\">Recent logs</button></form>\n          <form method=\"post\" action=\"/app/explore/?organization="); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:28:70
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:28:93
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:28:145
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.CSRFToken)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:28:162
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"query\" value=\"metrics | window 1h | limit 50\"><button class=\"secondary\" type=\"submit\">Recent metrics</button></form>\n          <form method=\"post\" action=\"/app/explore/?organization="); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:29:70
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:29:93
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:29:145
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.CSRFToken)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:29:162
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"query\" value=\"traces | window 1h | limit 50\"><button class=\"secondary\" type=\"submit\">Recent traces</button></form>\n          <form method=\"post\" action=\"/app/explore/?organization="); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:30:70
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:30:93
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:30:145
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.CSRFToken)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:30:162
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"query\" value=\"deployments | window 24h | limit 50\"><button class=\"secondary\" type=\"submit\">Recent deployments</button></form>\n        </div>\n      </div>\n      <form class=\"editor-card query-workbench\" method=\"post\" action=\"/app/explore/?organization="); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:33:102
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:33:125
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n        <input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:34:59
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.CSRFToken)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:34:76
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n        <label for=\"explore-query\">Query</label>\n        <textarea id=\"explore-query\" name=\"query\" required maxlength=\"16384\" spellcheck=\"false\">"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:36:101
		if __himesan_error := __himesan_sando.WriteRCDATA(__himesan_writer, (view.Query)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:36:114
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</textarea>\n        <p class=\"field-help\">Begin with <code>logs</code>, <code>metrics</code>, <code>traces</code>, or <code>deployments</code>. Every query has bounded time, rows, bytes, and memory.</p>\n        <button type=\"submit\">Run query</button>\n      </form>\n    </section>\n    "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:41:8
		if view.ErrorMessage != "" {
//line internal/site/explore.sando:41:39
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p class=\"form-error\" role=\"alert\">"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:41:78
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.ErrorMessage)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:41:98
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:41:105
		}
//line internal/site/explore.sando:41:109
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:42:8
		if view.Executed {
//line internal/site/explore.sando:42:29
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    <section class=\"query-results\" aria-labelledby=\"results-title\">\n      <div class=\"query-results-heading\"><div><p class=\"eyebrow\">Authorized result</p><h2 id=\"results-title\">Query results</h2></div>\n        <dl class=\"query-stats\">\n          <div><dt>Scanned rows</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:46:45
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Stats.ScannedRows)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:46:70
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>\n          <div><dt>Matched rows</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:47:45
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Stats.MatchedRows)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:47:70
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>\n          <div><dt>Scanned bytes</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:48:46
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Stats.ScannedBytes)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:48:72
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>\n          <div><dt>Execution</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:49:42
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Stats.Duration)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:49:64
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>\n        </dl>\n      </div>\n      "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:52:10
			if view.Stats.Truncated {
//line internal/site/explore.sando:52:38
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p class=\"live-status\"><strong>Result limit reached.</strong> Refine the query or deliberately choose a different bounded limit.</p>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/explore.sando:52:173
			}
//line internal/site/explore.sando:52:177
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:53:10
			if view.Stats.Approximate {
//line internal/site/explore.sando:53:40
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p class=\"live-status\"><strong>Approximate result.</strong> This answer uses an authorized aggregate projection.</p>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/explore.sando:53:159
			}
//line internal/site/explore.sando:53:163
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:54:11
			if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (ResultTable(view.Table))); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:54:37
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    </section>\n    "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/explore.sando:56:8
		}
//line internal/site/explore.sando:56:12
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n  </main>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:58:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteFooter())); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/explore.sando:58:22
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n</body>\n</html>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
