// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 131f6248343bf4c87cd3a2a525a2050cee13ad29a2e178d5ef4e996c65590dc9

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func Head(view HeadView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/head.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<meta name=\"description\" content=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:9:39
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Description)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:9:58
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n<link rel=\"canonical\" href=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:10:33
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.CanonicalURL)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:10:53
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n<link rel=\"manifest\" href=\"/manifest.webmanifest\">\n<link rel=\"stylesheet\" href=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:12:34
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Assets.StylePath)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:12:58
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n<script src=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:13:18
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Assets.ScriptPath)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:13:43
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" defer></script>\n<title>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:14:12
		if __himesan_error := __himesan_sando.WriteRCDATA(__himesan_writer, (view.Title)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/head.sando:14:25
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</title>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
