// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 df123546e9ef420a7ce574a528a984505176d15c8e6233582468bde1e5bc9ea6

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func IncidentInbox(view IncidentInboxView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/incidents.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<!doctype html>\n<html lang=\"en\">\n<head>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:9:11
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (Head(view.Head))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:9:29
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</head>\n<body>\n  <a class=\"skip-link\" href=\"#main\">Skip to content</a>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:12:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteHeader(true, "incidents", view.Organization.ID))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:12:61
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n  <main id=\"main\" data-open-incident-count=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:13:49
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.OpenCount)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:13:66
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n    <nav class=\"breadcrumbs\" aria-label=\"Breadcrumb\"><a href=\"/app/?organization="); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:14:86
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:14:109
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Overview</a><span aria-hidden=\"true\">/</span><span aria-current=\"page\">Incidents</span></nav>\n    <section class=\"app-intro\" aria-labelledby=\"incident-title\">\n      <div><p class=\"eyebrow\">Incident inbox · "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:16:53
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Organization.Name)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:16:78
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p><h1 id=\"incident-title\">What needs attention?</h1><p>Welcome, "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:16:148
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.DisplayName)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:16:167
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, ". Rules use bounded saved queries; this inbox keeps the human response durable and reviewable.</p></div>\n    </section>\n    <aside class=\"live-status\" data-events-url=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:18:53
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.EventsURL)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:18:70
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" hidden><p><strong>Incident evidence changed.</strong> <a href=\"/app/incidents/?organization="); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:18:168
		if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:18:191
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Refresh this inbox</a>.</p></aside>\n    <section class=\"offline-control\" aria-labelledby=\"offline-copy-title\"><div><h2 id=\"offline-copy-title\">Keep a careful offline copy</h2><p id=\"offline-copy-note\">This is opt-in. The saved copy excludes response controls, CSRF material, query text, telemetry values, actors, and project, environment, or service identifiers.</p></div><div><button class=\"secondary\" type=\"button\" data-cache-inbox data-offline-source=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:19:424
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.OfflineURL)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:19:442
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" data-offline-target=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:19:469
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.CacheKey)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:19:485
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" aria-describedby=\"offline-copy-note\" disabled>Save this inbox for offline use</button><p data-cache-status role=\"status\" aria-live=\"polite\">Offline saving requires service-worker support.</p></div></section>\n    "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:20:8
		if view.PushPublicKey != "" {
//line internal/site/incidents.sando:20:40
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<section class=\"offline-control\" aria-labelledby=\"push-title\"><div><h2 id=\"push-title\">Ask this browser to nudge you</h2><p id=\"push-note\">Optional Web Push sends one fixed message through the browser vendor: “Gamertan Observatory needs your attention.” It never includes an organization, host, service, severity, rule, incident identifier, count, or telemetry text.</p></div><div><button class=\"secondary\" type=\"button\" data-push-toggle data-push-public-key=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:20:508
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.PushPublicKey)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:20:529
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" data-push-organization=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:20:559
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:20:582
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" data-push-csrf=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:20:604
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.PushCSRF)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:20:620
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" aria-describedby=\"push-note\" disabled>Enable private incident nudges</button><p data-push-status role=\"status\" aria-live=\"polite\">Push requires service-worker and notification support.</p></div></section>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:20:829
		}
//line internal/site/incidents.sando:20:833
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    <section class=\"section-grid\" aria-labelledby=\"active-incidents\">\n      <div><p class=\"eyebrow\">Durable state</p><h2 id=\"active-incidents\">Incidents</h2></div>\n      <div class=\"incident-list\">\n      "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:24:10
		if len(view.Incidents) == 0 {
//line internal/site/incidents.sando:24:42
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p>No incidents have been opened.</p>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:24:82
		}
//line internal/site/incidents.sando:24:86
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:25:10
		for _, incident := range view.Incidents {
//line internal/site/incidents.sando:25:54
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        <article class=\"incident-card\" data-state=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:26:56
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (incident.State)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:26:73
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n          <div><p class=\"eyebrow\">"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:27:39
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.Severity)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:27:59
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, " · "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:27:67
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.State)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:27:84
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p><h3>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:27:96
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.Title)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:27:113
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</h3></div>\n          <dl><div><dt>Started</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:28:44
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.StartedAt)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:28:65
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div><div><dt>Updated</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:28:105
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.UpdatedAt)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:28:126
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:28:140
			if incident.SilencedUntil != "" {
//line internal/site/incidents.sando:28:176
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<div><dt>Silenced until</dt><dd>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:28:212
				if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.SilencedUntil)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:28:237
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:28:251
			}
//line internal/site/incidents.sando:28:255
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dl>\n          "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:29:14
			if view.CanManage && incident.State != "resolved" {
//line internal/site/incidents.sando:29:68
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n          <div class=\"incident-actions\" aria-label=\"Actions for "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:30:69
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (incident.Title)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:30:86
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n            <form method=\"post\" action=\"/app/incidents/"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:31:60
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (incident.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:31:74
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "/\"><input type=\"hidden\" name=\"organization_id\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:31:132
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:31:155
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:31:207
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ManageCSRF)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:31:225
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"action\" value=\"acknowledge\"><input type=\"hidden\" name=\"silence_duration\" value=\"\"><button class=\"secondary\" type=\"submit\">Acknowledge</button></form>\n            <form method=\"post\" action=\"/app/incidents/"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:60
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (incident.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:74
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "/\"><input type=\"hidden\" name=\"organization_id\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:132
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:155
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:207
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ManageCSRF)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:225
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"action\" value=\"silence\"><label for=\"silence-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:302
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (incident.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:316
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Silence for</label><select id=\"silence-"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:361
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (incident.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:32:375
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\" name=\"silence_duration\"><option value=\"15m\">15 minutes</option><option value=\"1h\">1 hour</option><option value=\"6h\">6 hours</option><option value=\"24h\">24 hours</option><option value=\"168h\">7 days</option></select><button class=\"secondary\" type=\"submit\">Silence</button></form>\n            <form method=\"post\" action=\"/app/incidents/"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:33:60
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (incident.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:33:74
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "/\"><input type=\"hidden\" name=\"organization_id\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:33:132
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:33:155
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:33:207
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ManageCSRF)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:33:225
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"action\" value=\"resolve\"><input type=\"hidden\" name=\"silence_duration\" value=\"\"><button class=\"secondary\" type=\"submit\">Resolve</button></form>\n          </div>\n          "); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:35:14
			}
//line internal/site/incidents.sando:35:18
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n        </article>\n      "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:37:10
		}
//line internal/site/incidents.sando:37:14
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      </div>\n    </section>\n    <section class=\"section-grid\" aria-labelledby=\"alert-rules\">\n      <div><p class=\"eyebrow\">Bounded evaluation</p><h2 id=\"alert-rules\">Alert rules</h2></div>\n      <div class=\"saved-grid\">\n      "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:43:10
		if len(view.Rules) == 0 {
//line internal/site/incidents.sando:43:38
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p>No alert rules yet.</p>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:43:67
		}
//line internal/site/incidents.sando:43:71
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:44:10
		for _, rule := range view.Rules {
//line internal/site/incidents.sando:44:46
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<article><p class=\"eyebrow\">"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:78
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (rule.Severity)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:94
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p><h3>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:106
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (rule.Name)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:118
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</h3><p>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:130
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (rule.Description)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:149
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p><dl><div><dt>Interval</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:187
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (rule.Interval)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:203
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div><div><dt>Status</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:241
			if rule.Enabled {
//line internal/site/incidents.sando:44:261
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "Enabled"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:44:271
			} else {
//line internal/site/incidents.sando:44:282
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "Disabled"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:44:293
			}
//line internal/site/incidents.sando:44:297
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:311
			if rule.LastEvaluatedAt != "" {
//line internal/site/incidents.sando:44:345
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<div><dt>Last evaluated</dt><dd>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:44:381
				if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (rule.LastEvaluatedAt)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:44:404
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:44:418
			}
//line internal/site/incidents.sando:44:425
			if rule.LastError != "" {
//line internal/site/incidents.sando:44:453
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<div><dt>Last result</dt><dd>Query unavailable</dd></div>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:44:513
			}
//line internal/site/incidents.sando:44:517
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dl></article>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:44:535
		}
//line internal/site/incidents.sando:44:539
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      </div>\n    </section>\n    "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:47:8
		if view.CanManage {
//line internal/site/incidents.sando:47:30
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    <section class=\"section-grid\" aria-labelledby=\"create-alert\">\n      <div><p class=\"eyebrow\">Organization workshop</p><h2 id=\"create-alert\">Create an alert rule</h2><p>A rule counts rows returned by one saved query. Consecutive matches allow brief noise to remain pending before an incident fires.</p></div>\n      <form class=\"editor-card\" method=\"post\" action=\"/app/alert-rules/\">\n        <input type=\"hidden\" name=\"organization_id\" value=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:51:64
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.Organization.ID)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:51:87
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:51:139
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.ManageCSRF)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:51:157
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n        <label for=\"alert-name\">Name</label><input id=\"alert-name\" name=\"name\" required maxlength=\"128\">\n        <label for=\"alert-description\">Description</label><textarea id=\"alert-description\" name=\"description\" required maxlength=\"1024\"></textarea>\n        <label for=\"alert-query\">Saved query</label><select id=\"alert-query\" name=\"saved_query_id\" required><option value=\"\">Choose a saved query</option>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:54:158
			for _, item := range view.SavedQueries {
//line internal/site/incidents.sando:54:201
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<option value=\""); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:54:220
				if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (item.ID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:54:230
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:54:236
				if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (item.Name)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:54:248
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</option>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:54:260
			}
//line internal/site/incidents.sando:54:264
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</select>\n        <div class=\"field-grid\"><div><label for=\"alert-severity\">Severity</label><select id=\"alert-severity\" name=\"severity\" required><option value=\"information\">Information</option><option value=\"warning\" selected>Warning</option><option value=\"critical\">Critical</option></select></div><div><label for=\"alert-interval\">Evaluate every</label><select id=\"alert-interval\" name=\"evaluation_interval\" required><option value=\"15s\">15 seconds</option><option value=\"30s\">30 seconds</option><option value=\"1m\" selected>1 minute</option><option value=\"5m\">5 minutes</option><option value=\"15m\">15 minutes</option></select></div><div><label for=\"alert-matches\">Minimum matching rows</label><input id=\"alert-matches\" type=\"number\" name=\"minimum_matches\" min=\"1\" max=\"100000\" value=\"1\" required></div><div><label for=\"alert-confirmations\">Consecutive evaluations</label><input id=\"alert-confirmations\" type=\"number\" name=\"required_consecutive\" min=\"1\" max=\"10\" value=\"2\" required></div></div>\n        "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:56:12
			if len(view.SavedQueries) == 0 {
//line internal/site/incidents.sando:56:47
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<button type=\"submit\" disabled>Create alert rule</button>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:56:107
			} else {
//line internal/site/incidents.sando:56:118
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<button type=\"submit\">Create alert rule</button>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/incidents.sando:56:169
			}
//line internal/site/incidents.sando:56:173
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      </form>\n    </section>\n    "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/incidents.sando:59:8
		}
//line internal/site/incidents.sando:59:12
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n  </main>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:61:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteFooter())); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/incidents.sando:61:22
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n</body>\n</html>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
