// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 dd75f02614b8688552456737ff2bfd5e9625897254989ab8ae2098b5fd5fccc9

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func Login(view LoginView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/login.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<!doctype html>\n<html lang=\"en\">\n<head>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:9:11
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (Head(view.Head))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:9:29
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</head>\n<body>\n  <a class=\"skip-link\" href=\"#main\">Skip to content</a>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:12:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteHeader(false, "", ""))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:12:35
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n  <main id=\"main\" class=\"auth-shell\">\n    <section class=\"auth-card\" aria-labelledby=\"login-title\">\n      <p class=\"eyebrow\">Private workshop</p>\n      <h1 id=\"login-title\">Sign in to Observatory</h1>\n      <p>Use the local account created by <code>observatory admin bootstrap</code>.</p>\n      "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:18:10
		if view.ErrorMessage != "" {
//line internal/site/login.sando:18:41
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p class=\"form-error\" role=\"alert\">"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/login.sando:18:80
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.ErrorMessage)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/login.sando:18:100
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/login.sando:18:107
		}
//line internal/site/login.sando:18:111
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      <form method=\"post\" action=\"/login/\">\n        <input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:20:59
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.CSRFToken)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:20:76
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n        <label for=\"identifier\">Username or email</label>\n        <input id=\"identifier\" name=\"identifier\" autocomplete=\"username\" required maxlength=\"320\">\n        <label for=\"password\">Password</label>\n        <input id=\"password\" name=\"password\" type=\"password\" autocomplete=\"current-password\" required maxlength=\"1024\">\n        <button type=\"submit\">Sign in</button>\n      </form>\n    </section>\n  </main>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:29:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteFooter())); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/login.sando:29:22
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n</body>\n</html>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
