// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 47e648ceed0893244cf41692e7a3d7ecc66a0cba09554e45b0d3dda3567bdfd7

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func OfflineIncidentInbox(view OfflineIncidentView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/offline_incidents.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<!doctype html>\n<html lang=\"en\">\n<head>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:9:11
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (Head(view.Head))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:9:29
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</head>\n<body>\n  <a class=\"skip-link\" href=\"#main\">Skip to content</a>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:12:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteHeader(true, "incidents", view.Organization.ID))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:12:61
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n  <main id=\"main\" data-open-incident-count=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:13:49
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (len(view.Incidents))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:13:71
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n    <nav class=\"breadcrumbs\" aria-label=\"Breadcrumb\"><a href=\"/app/\">Overview</a><span aria-hidden=\"true\">/</span><span aria-current=\"page\">Saved incident inbox</span></nav>\n    <section class=\"app-intro\" aria-labelledby=\"offline-incident-title\"><div><p class=\"eyebrow\">Offline snapshot · "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:15:121
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.Organization.Name)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:15:146
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p><h1 id=\"offline-incident-title\">Saved incident inbox</h1><p>Captured "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:15:223
		if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.CapturedAt)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:15:241
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, ". Response actions are intentionally unavailable offline.</p></div></section>\n    <section class=\"section-grid\" aria-labelledby=\"saved-incidents\"><div><p class=\"eyebrow\">Read-only</p><h2 id=\"saved-incidents\">Incidents</h2></div><div class=\"incident-list\">\n      "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:17:10
		if len(view.Incidents) == 0 {
//line internal/site/offline_incidents.sando:17:42
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p>No open incidents were present in this snapshot.</p>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:17:100
		}
//line internal/site/offline_incidents.sando:17:104
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:18:10
		for _, incident := range view.Incidents {
//line internal/site/offline_incidents.sando:18:54
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<article class=\"incident-card\" data-state=\""); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:101
			if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (incident.State)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:118
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\"><p class=\"eyebrow\">"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:143
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.Severity)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:163
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, " · "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:171
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.State)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:188
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p><h3>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:200
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.Title)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:217
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</h3><dl><div><dt>Started</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:255
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.StartedAt)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:276
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div><div><dt>Updated</dt><dd>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:316
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.UpdatedAt)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:337
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:351
			if incident.SilencedUntil != "" {
//line internal/site/offline_incidents.sando:18:387
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<div><dt>Silenced until</dt><dd>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/offline_incidents.sando:18:423
				if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (incident.SilencedUntil)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/offline_incidents.sando:18:448
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dd></div>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/offline_incidents.sando:18:462
			}
//line internal/site/offline_incidents.sando:18:466
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</dl></article>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/offline_incidents.sando:18:484
		}
//line internal/site/offline_incidents.sando:18:488
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    </div></section>\n    <section class=\"section-grid\" aria-labelledby=\"offline-boundary\"><div><p class=\"eyebrow\">Privacy boundary</p><h2 id=\"offline-boundary\">This copy stays on this browser.</h2></div><div><p>It contains the organization name, incident titles, and states, but no response controls, CSRF tokens, query text, telemetry values, actor identifiers, or project, environment, or service identifiers. Signing out while online clears saved private snapshots.</p><p><a class=\"button secondary\" href=\"/app/\">Reconnect and refresh</a></p></div></section>\n  </main>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:22:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteFooter())); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline_incidents.sando:22:22
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n</body>\n</html>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
