// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 00fe79c601abcfc98b766fbb7332552b31cc92968251972bd24715f990812f09

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func Offline(view OfflineView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/offline.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<!doctype html><html lang=\"en\"><head>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline.sando:7:42
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (Head(view.Head))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline.sando:7:60
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</head><body><a class=\"skip-link\" href=\"#main\">Skip to content</a>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline.sando:7:130
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteHeader(false, "", ""))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline.sando:7:158
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<main id=\"main\"><section class=\"hero\"><p class=\"eyebrow\">Offline</p><h1>The evidence is still safe.</h1><p class=\"lede\">Observatory cannot reach the server right now. A previously saved incident inbox remains available from its usual address; otherwise, reconnect before viewing private organization data.</p><p><a class=\"button secondary\" href=\"/app/\">Try Observatory again</a></p></section></main>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline.sando:7:561
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteFooter())); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/offline.sando:7:576
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</body></html>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
