// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 75a8b350f1635bc7a9ba4feb50aa4bc3b151783a3ebee72fc0e1947f7787c320

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func Password(view PasswordView) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/password.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<!doctype html>\n<html lang=\"en\">\n<head>"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:9:11
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (Head(view.Head))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:9:29
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</head>\n<body>\n  <a class=\"skip-link\" href=\"#main\">Skip to content</a>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:12:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteHeader(false, "", ""))); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:12:35
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n  <main id=\"main\" class=\"auth-shell\">\n    <section class=\"auth-card\" aria-labelledby=\"password-title\">\n      <p class=\"eyebrow\">One careful first step</p>\n      <h1 id=\"password-title\">Choose your password</h1>\n      <p>The bootstrap credential is single-purpose. Replace it now; Observatory will end every session and ask you to sign in again.</p>\n      "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:18:10
		if view.ErrorMessage != "" {
//line internal/site/password.sando:18:41
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<p class=\"form-error\" role=\"alert\">"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/password.sando:18:80
			if __himesan_error := __himesan_sando.WriteText(__himesan_writer, (view.ErrorMessage)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/password.sando:18:100
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "</p>"); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/password.sando:18:107
		}
//line internal/site/password.sando:18:111
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      <form method=\"post\" action=\"/account/password/\">\n        <input type=\"hidden\" name=\"csrf_token\" value=\""); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:20:59
		if __himesan_error := __himesan_sando.WriteAttr(__himesan_writer, (view.CSRFToken)); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:20:76
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">\n        <label for=\"current-password\">Temporary password</label>\n        <input id=\"current-password\" name=\"current_password\" type=\"password\" autocomplete=\"current-password\" required maxlength=\"1024\">\n        <label for=\"new-password\">New password</label>\n        <input id=\"new-password\" name=\"new_password\" type=\"password\" autocomplete=\"new-password\" required minlength=\"12\" maxlength=\"1024\">\n        <label for=\"confirm-password\">Confirm new password</label>\n        <input id=\"confirm-password\" name=\"confirm_password\" type=\"password\" autocomplete=\"new-password\" required minlength=\"12\" maxlength=\"1024\">\n        <button type=\"submit\">Change password and sign out</button>\n      </form>\n    </section>\n  </main>\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:31:7
		if __himesan_error := __himesan_sando.Render(__himesan_render_context, __himesan_writer, (SiteFooter())); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/password.sando:31:22
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n</body>\n</html>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
