// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 df9cf0c1ef86d0317606ba4eccb618cfe2d0925ef83dd572df78beaa6d2c254f

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func SiteFooter() __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/site_footer.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/site_footer.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<footer class=\"site-footer\">\n  <p>Self-hosted, evidence-minded observability. Built and tended by Gamertan.</p>\n</footer>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
