// Code generated by himesan; DO NOT EDIT.
// himesan:compiler v1.0.0-beta.2
// himesan:runtime-abi sando.v1
// himesan:source-sha256 5e30e1ad98c586ffdc566d3688d3288d918faf5645804cd18ef6233a1e250e6b

package site

import (
	__himesan_context "context"
	__himesan_sando "gamertan.com/sandwich-hime/sando"
	__himesan_io "io"
)

var _ = __himesan_sando.ABISandoV1

func SiteHeader(authenticated bool, current string, organizationID string) __himesan_sando.Component {
	return __himesan_sando.ComponentFunc(func(__himesan_render_context __himesan_context.Context, __himesan_writer __himesan_io.Writer) error {
		_ = __himesan_render_context
//line internal/site/site_header.sando:5:3
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n"); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/site_header.sando:6:46
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n<header class=\"site-header\">\n  "); __himesan_error != nil {
			return __himesan_error
		}
//line internal/site/site_header.sando:8:6
		if authenticated {
//line internal/site/site_header.sando:8:27
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    <a class=\"wordmark\" href=\"/app/?organization="); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/site_header.sando:9:54
			if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (organizationID)); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/site_header.sando:9:71
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Gamertan Observatory</a>\n    <nav aria-label=\"Primary\">\n      "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/site_header.sando:11:10
			if current == "overview" {
//line internal/site/site_header.sando:11:39
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<a aria-current=\"page\" href=\"/app/?organization="); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:11:91
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (organizationID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:11:108
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Overview</a>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:11:125
			} else {
//line internal/site/site_header.sando:11:136
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<a href=\"/app/?organization="); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:11:168
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (organizationID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:11:185
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Overview</a>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:11:202
			}
//line internal/site/site_header.sando:11:206
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/site_header.sando:12:10
			if current == "explore" {
//line internal/site/site_header.sando:12:38
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<a aria-current=\"page\" href=\"/app/explore/?organization="); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:12:98
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (organizationID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:12:115
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Explore</a>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:12:131
			} else {
//line internal/site/site_header.sando:12:142
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<a href=\"/app/explore/?organization="); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:12:182
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (organizationID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:12:199
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Explore</a>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:12:215
			}
//line internal/site/site_header.sando:12:219
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/site_header.sando:13:10
			if current == "dashboards" {
//line internal/site/site_header.sando:13:41
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<a aria-current=\"page\" href=\"/app/?organization="); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:13:93
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (organizationID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:13:110
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "#dashboards\">Dashboards</a>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:13:140
			} else {
//line internal/site/site_header.sando:13:151
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<a href=\"/app/?organization="); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:13:183
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (organizationID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:13:200
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "#dashboards\">Dashboards</a>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:13:230
			}
//line internal/site/site_header.sando:13:234
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n      "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/site_header.sando:14:10
			if current == "incidents" {
//line internal/site/site_header.sando:14:40
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<a aria-current=\"page\" href=\"/app/incidents/?organization="); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:14:102
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (organizationID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:14:119
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Incidents</a>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:14:137
			} else {
//line internal/site/site_header.sando:14:148
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "<a href=\"/app/incidents/?organization="); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:14:190
				if __himesan_error := __himesan_sando.WriteURL(__himesan_writer, (organizationID)); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:14:207
				if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\">Incidents</a>"); __himesan_error != nil {
					return __himesan_error
				}
//line internal/site/site_header.sando:14:225
			}
//line internal/site/site_header.sando:14:229
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    </nav>\n  "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/site_header.sando:16:6
		} else {
//line internal/site/site_header.sando:16:17
			if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n    <a class=\"wordmark\" href=\"/\">Gamertan Observatory</a>\n    <nav aria-label=\"Primary\"><a href=\"/login/\">Sign in</a></nav>\n  "); __himesan_error != nil {
				return __himesan_error
			}
//line internal/site/site_header.sando:19:6
		}
//line internal/site/site_header.sando:19:10
		if __himesan_error := __himesan_sando.WriteString(__himesan_writer, "\n</header>\n"); __himesan_error != nil {
			return __himesan_error
		}
		return nil
	})
}
